"use client";

import { motion } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import styles from "./Loader.module.css";
import {
  playIntroWindow,
  releaseIntroFilm,
} from "@/lib/introWindow";
import type { HeroInsets } from "./types";

// The board's word. It used to be three groups — "MG", "N", "HW" — because
// stage 1 slid the outer pairs off and turned the centre letter into the
// window. Nothing splits any more, so it is one word.
const LETTERS = ["M", "G", "N", "H", "W"];
const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
// ── EASING ───────────────────────────────────────────────────────────────
// TWO CURVES. One for opacity, one for the window, and they are different
// KINDS of thing — a cubic-bezier and a generated spring.
//
// OPACITY: EASE_OUT. y1 = 1 makes it near-exponential, delivering most of its
// output inside the first tenth of its duration. On a fade that is exactly
// right: a cross-fade 90% done early reads as decisive, and there is no
// position for the eye to track. On GEOMETRY it is a pop followed by a creep —
// measured, driving the window open on it put 21% of the total travel into
// 150ms and then 3% into the next 150ms. Board fade, veil and progress bar
// only, and nothing else, ever.
const EASE_OUT = [0.23, 1, 0.32, 1] as const;
const SMOOTH = [0.62, 0, 0.2, 1] as const; // stage-0 idles + the short path

// THE WINDOW: A SPRING, AND IT IS THE ONLY CURVE THE GEOMETRY TOUCHES.
// Generated by Motion's own spring solver at perceptual duration 0.9s,
// bounce 0.12 — a 0.23% overshoot (k peaks at 1.0023), enough to feel alive
// and far too small to read as a bounce. It is a `linear()` easing with 37
// control points because that is the only CSS easing that can express a
// spring; no cubic-bezier approximates one, which is the whole reason the
// bezier era below ended.
//
// ⚠️ IT IS A STRING AND IT GOES STRAIGHT TO `element.animate()`. Do not
// "convert" it to a tuple, and do not hand it to a framer `transition` — see
// lib/introWindow.ts on why a MotionValue is never accelerated. `linear()` is
// supported by WAAPI and Chrome keeps such a transform animation on the
// compositor: VERIFIED, 0 RasterTasks and 0.0ms of paint across the whole
// expansion. If a browser ever rejects the string, `element.animate()` throws
// rather than falling back, which is what we want — a silent fallback would
// put five layers on five different curves.
//
// ── WHAT THIS REPLACED, SO THAT NOBODY REBUILDS IT ──
// The window used to open in FOUR segments: a closed head, an ease-out open to
// 86% of a "postcard" size, a linear pass ACROSS that postcard, and an
// ease-in-out grow-out. That staging was never in the brief; it was invented
// to fix a stall and it is what made the reveal read as staged rather than as
// one expansion. Its constants (WIN_IN, WIN_OUT, EASE_WINDOW, EASE_MORPH,
// LINEAR, T_POST_IN, T_POST_OUT) are all deleted.
// Two findings from that era are still worth keeping, because they are about
// JOINS and any future multi-segment timeline will hit them again:
//   • an iOS sheet ENTRANCE curve on a morph — EASE_DRAWER [0.32, 0.72, 0, 1]
//     — put 60% of the window's travel into one 200ms burst, and with x2 = 0
//     its tail flattened so far out that the last 250ms carried 1.2% of the
//     travel. Category error, not a tuning miss.
//   • a curve with y1 = 0 starts at EXACTLY zero velocity, so handing it a
//     segment that is already moving costs a measured hesitation: 8‥11px of
//     travel in the 40ms tick after the join against 24px before it.
// A spring has one segment and no joins, so neither can happen here — which is
// the strongest argument for it after the shape itself.
// SEGMENT A — the point settles out to the hold. REST TO REST, so ease-in-out
// is the correct category and easeInOutCubic is the plain choice. Its gentle
// start is the entire reason this segment exists rather than a spring: a
// front-loaded curve had the aperture past 100px within ~50ms of becoming
// visible, so the small phase registered rather than read.
const EASE_SETTLE = "cubic-bezier(0.65, 0, 0.35, 1)";

// SEGMENT B — the hold releases to full bleed. STARTS FROM REST, which is what
// a spring models, so a spring is right here and only here. Generated by
// Motion's solver at perceptual duration 0.6s, bounce 0.12 — it solves to
// 750ms and it is GIVEN 750ms (see T_HOLD_OUT → REVEAL_MS), so the curve runs
// at the duration it was solved for rather than being time-compressed into a
// rounder slot. Peak overshoot 1.0028.
const SPRING_OUT =
  "linear(0, 0.0317, 0.1081, 0.2078, 0.316, 0.4231, 0.5232, 0.6132, 0.6915, " +
  "0.7581, 0.8136, 0.8588, 0.8951, 0.9237, 0.9459, 0.9628, 0.9754, 0.9847, " +
  "0.9913, 0.9959, 0.999, 1.001, 1.0022, 1.0028, 1)";

// THE JOIN AT T_HOLD_OUT IS NOT THE JOIN THAT BROKE BEFORE, and the difference
// is worth stating because the fix from that round looks like it should apply
// here and must not be carried over. That defect was a MOVING segment (a
// constant 0.49px/ms pass) handing to a curve whose entry velocity was exactly
// zero — a genuine discontinuity, measured as 8‥11px of travel in the 40ms tick
// after the join against 24px before it. Here BOTH SIDES OF EVERY JOIN ARE AT
// REST: the settle decelerates into a dead hold and the spring is released from
// it. Zero entry velocity is not a defect against a stationary neighbour, it is
// the only correct value, so do NOT give SPRING_OUT a nonzero opening slope.
// Segments between two identical values need a curve only because WAAPI wants
// one; `linear` between equal endpoints is exactly still.
const HOLD = "linear";
const FLIP_TICK = 46; // base ms per alphabet step (varied per letter)
const MIN_TIME = 2600; // minimum loading time on screen (ms)
const MIN_TIME_REPEAT = 150; // tiny floor on repeat visits / reduced motion
const SETTLE_CAP = 1600; // max wait after ready for the slowest flap to land
const VIDEO_WAIT = 1000; // max ms to keep polling for the hero <video> to mount
const HARD_CAP = 8000; // never hang longer than this waiting on assets
// Absolute backstop for the whole intro. Must exceed the longest *legitimate*
// completion (assets force-ready at HARD_CAP → up to SETTLE_CAP to stage 1 →
// ~1.3s reveal → ~0.1s hand-off ≈ 11.7s) so it only ever fires if the normal
// exits stalled — never cutting the full-path reveal short.
const SAFETY_CAP = 15000;
const FADE_MS = 550; // cream cross-fade on repeat-visit / reduced-motion path
const SEEN_KEY = "mgnhw:introSeen";

// ── Stage-1 reveal timeline (ms from stage-1 start) ─────────────────────────
// A POINT, A LOOK, THEN THE ROOM. Three moving ideas and one still one:
//
//   0‥200    the board fades out IN PLACE and recedes to 96%. It does not
//            split and it does not travel, so no frame can show a legible
//            letter sliced by a screen edge — the failure mode the old
//            slide-apart spent three tunings fencing off. The recede is what
//            separates "left" from "blinked out": a pure opacity fade on a
//            stationary object reads as a bug.
//   0‥200    the window sits at k = kPoint, ~3px, under an opaque veil.
// 200‥320    the veil fades. Its only job is to stop a 3px dot HARD-POPPING
//            into existence — a beat of materialisation, not a reveal of its
//            own, and it must not linger: the reader should be watching the
//            point grow, not watching a cream sheet clear.
// 200‥560    k: kPoint → kHold on EASE_SETTLE. 360ms.
// 560‥730    HOLD, DEAD STILL, 170ms. The picture sits at a size it can be
//            looked at. This is not the beat that was removed two rounds ago:
//            that one was a CONSTANT-VELOCITY PASS across a "postcard", i.e.
//            motion pretending to be stillness, and it read as staged because
//            it was. This is a stop. It is also structurally safer than the
//            thing it resembles — see the note on the join at SPRING_OUT.
// 730‥1480   k: kHold → 1 on SPRING_OUT. 750ms, the duration the spring was
//            solved for.
//
// MEASURED (`node scripts/probe-loader-hold.mjs`, 1440×900, two runs, and the
// two runs agree to a pixel). The whole reason this shape exists is the size
// of the aperture early on, so that is what gets graded:
//            ct   250   300   350   400   450   500
//             k 0.0066 0.025 0.071 0.158 0.213 0.234
//            px     9    35   102   228   306   337
// It crosses 100px at ct 350, 200px at ct 393 and the held size at ct 551.
// The veil is effectively clear by ~215ms, so the aperture is VISIBLY under
// 100px for ~135ms and under 200px for ~180ms — against ~50ms when one
// front-loaded spring ran the whole reveal. Then 170ms of dead stop.
// THE FIRST TWO COLUMNS ARE THE POINT: at ct 250 the hole is NINE PIXELS.
// easeInOutCubic is why — it spends its opening third barely moving, which is
// exactly the property a spring cannot have.
const REVEAL_MS = 1480;
const T_WIN_OPEN = 200;
const T_HOLD_IN = 560;
const T_HOLD_OUT = 730;
const BOARD_FADE_S = 0.3; // the board's exit — an exit, so EASE_OUT
const BOARD_RECEDE = 0.96;
// 200‥320. EASE_OUT is near-expo, so the nominal end is not the useful number:
// the veil is under 5% opacity within ~50ms of starting. Grade this pair by
// how big the dot is when the veil clears, never by delay + duration.
const VEIL_DELAY_S = 0.2;
const VEIL_FADE_S = 0.12;

// ── THE POINT OF LIGHT ──
// A PX FLOOR, NOT A FRACTION, and that distinction is the whole constant. As a
// fraction the "point" would grow with the viewport — 3px on a phone and 8px
// on a 4K display — and the thing that reads as a point is an absolute size,
// not a share of the screen. Divided through by vw at use, so it is the same
// dot everywhere.
// NOT 0: a hole with no area has no picture in it, so the first visible frame
// would be a hard pop from nothing rather than a point already present.
const SEED_PX_MIN = 3;

// ── THE HOLD'S SIZE ──
// Proportional so it holds at any viewport, floored because below ~130px a
// crop of this film stops reading as a picture and starts reading as a colour
// swatch, capped so that on a narrow window the "look at it" moment is not
// just a slightly inset hero. 0.24 of a 1440 viewport is 345px, which is the
// size that measured legible — the frame read unmistakably as a dish.
// These three are the postcard's old constants, restored deliberately: the
// SIZE was never what was wrong with the removed beat, the MOTION across it
// was.
const HOLD_VW = 0.24;
const HOLD_MIN_PX = 260;
const HOLD_MAX_VW = 0.56;
// NO SEED_AR AND NO SEED_R ANY MORE.
// The aperture is a centred k·vw × k·vh rect, so its aspect ratio IS the
// viewport's at every k — which is exactly what lets the film fill it with one
// uniform `scale(k)` and never be stretched. A 16:9 postcard on a 16:10
// viewport would have needed the film to scale NON-uniformly, and that is the
// 72.9%-worst-aspect-error dead end lib/introWindow.ts records.
// The 10px corner radius went with the clip-path. Four rectangular panels
// cannot round the hole they leave between them, and every way of putting it
// back costs what this rewrite was for: a rounded `overflow: hidden` box
// re-introduces a clip, and a radius on the scaling film arrives as radius × k
// — 10px at the postcard only if it were 42px at full bleed, where the hero
// has none.

// The window is full-bleed the instant the reveal completes (insets are all
// zero), so there is no residual cream to cross-fade — this is only a paint
// buffer before the overlay unmounts, not a hold.
const HANDOFF_MS = 100;

// The four shutters, in the order lib/introWindow.ts reads them. The axis is
// the whole difference between them: a top/bottom panel is squashed on Y, a
// left/right panel on X, and the transform-origin that anchors each one to its
// own edge lives in the stylesheet next to the class. Both pairs take the SAME
// scale value, which is the property that makes a centred uniform aperture one
// number instead of four.
const SHUTTERS = [
  { cls: "shutterTop", axis: "scaleY" },
  { cls: "shutterBottom", axis: "scaleY" },
  { cls: "shutterLeft", axis: "scaleX" },
  { cls: "shutterRight", axis: "scaleX" },
] as const;
// ── Where the film is when the window opens ──
// ⚠️ COUPLED TO THIS EXACT CUT OF belly-hero.mp4 — recut or re-encode the
// clip and this number is silently wrong, in a way nobody will connect back
// here.
//
// ⚠️ AND THE CLIP WAS RETIMED. Every timestamp below moved by 25/24 when the
// hero clips went from 25fps to 24fps. That was not a compression change: at
// 25fps a frame lasts 4.8 refreshes of a 120Hz panel, so the browser holds
// each one for 5 refreshes then 4 to catch up — textbook cadence judder,
// ±8.3ms, and most visible during the reveal because that is when the picture
// first gets big enough to read motion in. 24fps is exactly 5 refreshes. The
// retime invented no frames: `ffmpeg -itsscale 1.0416667 -i in.mp4 -c copy`
// rescales the container's timestamps and passes the coded H.264 through
// untouched (verified frame-for-frame, 535 -> 535). The film simply plays
// 4.17% slower. Confirmed in a blind A/B before it shipped.
//
// The clip is a fast montage (15 cuts in 22.29s, mean shot 1.115s) and the
// reveal needs ~1.31s of UNCUT film — MEASURED: the veil clears at ~285ms
// (ct 6.33), full bleed lands at ct 7.53 and the overlay's last frame is at
// ct ~7.64. Only one shot is that long, and it runs ct 6.25‥7.875. Seeking to
// 6.083 starts 167ms BEFORE that shot on purpose: the in-cut at 6.25 then
// happens at t+167ms, while the veil is still opaque, so the reader never sees
// it.
// ⚠️ THE 7.875 OUT-CUT IS A SOFT CUT AND ffmpeg's DEFAULT SCENE THRESHOLD
// MISSES IT. `select=gt(scene,0.4)` reports only 6.250 and 8.792, which reads
// as a luxurious 2.54s shot and 1.3s of spare margin. It is not: at
// `scene,0.15` the 7.875 cut appears. Anyone re-deriving this cut map to
// justify a longer reveal must use the lower threshold, or they will lengthen
// REVEAL_MS straight through a cut and not see it in the numbers.
// Seeking to 6.083 means the in-cut into that shot lands at t+167ms, while
// the veil is still fully opaque, and the expansion runs across the whole of
// the rest of it — landing full bleed on a lit pan of seafood being ladled.
// TWO THINGS THIS CONSTANT NO LONGER CARES ABOUT, because the reveal became a
// zoom and then lost its postcard beat: the window is not a centre-band CROP
// any more (it shows the whole frame, scaled), and there is no held moment for
// a particular sub-second of footage to have to carry. What survives, and what
// actually pins this number, is SHOT LENGTH — the expansion must not cross a
// cut — plus the in-cut hiding under the veil.
// MARGIN: the overlay unmounts at REVEAL_MS + HANDOFF_MS = 1580ms, i.e. at
// ct 6.083 + 1.58 = 7.663 against the out-cut at 7.875. MEASURED across three
// runs the overlay's last frame sits at ct 7.594 / 7.632 / 7.640, so ~235‥280ms
// — a little better than the arithmetic, because the film advances marginally
// slower than wall-clock under load (1.55s of footage over a 1.59s reveal).
// Do not bank that difference; it is load-dependent. Call it ~240ms. THE HISTORY MATTERS BECAUSE IT SHOWS THE EXCHANGE RATE: it was
// ~120ms at REVEAL_MS 1500; cutting the reveal to 1300 bought ~200ms back and
// the 25→24fps retime added ~65ms more (the shot itself got 4.17% longer in
// seconds); putting a 170ms hold back and giving the release spring the 750ms
// it was solved for took REVEAL_MS to 1480 and spent ~180ms of it again.
// This is still the tightest coupling in the file: LENGTHENING the reveal
// spends the remaining margin 1ms for 1ms, and past ~1.79s it cuts mid-shot.
// There is no third thing to trade — the next person who wants a longer look
// at the held frame is choosing between the cut and the hold.
// NOT 0: the opening shot is fine footage full-frame but EMPTY across the
// dead-centre band (band sd 2.5‥9.4 vs 3.55+ for a picture) — the old
// naked-slab read was a framing coincidence, not bad footage.
// NOT 6.25, even though it is an exact IDR keyframe with near-identical
// content. The original reason no longer holds, and is recorded here so that
// nobody re-derives it: at REVEAL_MS = 1500 that shot's out-cut landed inside
// the overlay-unmount window, and a cut on the handoff frame reads as a
// glitch. At REVEAL_MS = 1300 the unmount moved to t+1400 and that collision
// is gone. What is left is margin — seeking to the keyframe leaves ~167ms of
// shot after the unmount, seeking to 6.083 leaves ~390ms — and the 167ms of
// the PREVIOUS shot that 6.083 costs is spent entirely under an opaque veil.
// The keyframe saves ~8ms of decode and does not buy back half the margin. Do
// not "simplify" this to the keyframe, and note that if REVEAL_MS ever goes
// back up the old collision comes back with it.
// STANDING REQUIREMENT if the film ever changes: one continuous shot of
// ≥~1.4s with subject matter in the middle third of the frame, placed at
// the HEAD of the clip — then this constant returns to 0 and the coupling
// disappears entirely. And whatever replaces it must be 24, 30 or 60fps:
// anything that does not divide 120 evenly brings the cadence judder back.
const HERO_SEEK_S = 6.083;

type Vp = { w: number; h: number };

// `Rect` and `holePath()` are gone with the clip-path. They built a
// `path(evenodd, …)` whose outer subpath was the viewport and whose inner
// subpath was the hole, emitting an identical command sequence at any geometry
// so framer could interpolate it cleanly. It interpolated beautifully and
// repainted the entire viewport on every displayed frame; lib/introWindow.ts
// carries the trace numbers that retired it.


/**
 * One split-flap cell. While loading it cycles the whole alphabet on a loop;
 * once `settle` is true it stops the next time it reaches its target letter,
 * so the word locks in with a staggered cascade.
 */
function FlipLetter({
  final,
  settle,
  startDelay = 0,
  reduce = false,
  onLock,
}: {
  final: string;
  settle: boolean;
  startDelay?: number;
  reduce?: boolean;
  onLock?: () => void;
}) {
  const targetIdx = Math.max(0, ALPHABET.indexOf(final.toUpperCase()));
  const [idx, setIdx] = useState(reduce ? targetIdx : 0);
  const settleRef = useRef(settle);
  settleRef.current = settle;
  const lockedRef = useRef(false);
  const lock = () => {
    if (!lockedRef.current) {
      lockedRef.current = true;
      onLock?.();
    }
  };

  useEffect(() => {
    if (reduce) {
      setIdx(targetIdx);
      lock();
      return;
    }
    let i = 0;
    let timer: ReturnType<typeof setTimeout>;
    // each flap runs at its own pace, so they desync and lock in at
    // different moments like a real split-flap board
    const baseTick = FLIP_TICK * (0.78 + Math.random() * 0.7);
    const begin = startDelay + Math.random() * 160;

    const step = () => {
      i = (i + 1) % 26;
      if (settleRef.current && i === targetIdx) {
        setIdx(targetIdx); // reached its letter -> stop
        lock();
        return;
      }
      setIdx(i);
      // a little mechanical jitter on every flip
      timer = setTimeout(step, baseTick * (0.82 + Math.random() * 0.4));
    };

    const start = setTimeout(step, begin);
    return () => {
      clearTimeout(start);
      clearTimeout(timer);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reduce, targetIdx, startDelay]);

  const ch = ALPHABET[idx];
  return (
    <span className={styles.flip}>
      <motion.span
        key={ch}
        className={styles.flipInner}
        initial={{
          transform: reduce ? "rotateX(0deg)" : "rotateX(-78deg)",
          opacity: reduce ? 1 : 0.4,
        }}
        animate={{ transform: "rotateX(0deg)", opacity: 1 }}
        transition={{ duration: 0.16, ease: [0.2, 0.7, 0.3, 1] }}
      >
        {ch}
      </motion.span>
    </span>
  );
}

/**
 * Loading screen + intro:
 *  stage 0 — split-flap board scrambles while assets load; a progress bar at
 *            the bottom fills. When loading completes the letters lock to MGNHW.
 *  stage 1 — the board fades out in place; four cream shutters open a window
 *            from a ~3px point in the middle of the screen and the film SCALES
 *            UP INTO IT rather than being uncovered; it settles out to a size
 *            that can be looked at, holds dead still for 170ms, then springs
 *            to full bleed, revealing the video behind the cream
 *            overlay. The hero's own lockup arrives after the hand-off.
 *  stage 2 — hand off to the page (onDone).
 *
 * On a repeat visit (or with prefers-reduced-motion) the long choreography is
 * skipped: once assets are ready the cream overlay just cross-fades away.
 */
export default function Loader({
  insets,
  onDone,
}: {
  insets: HeroInsets;
  onDone: () => void;
}) {
  const [stage, setStage] = useState(0);
  const [vp, setVp] = useState<Vp | null>(null);
  const [progress, setProgress] = useState(0);
  const [ready, setReady] = useState(false);
  const [locked, setLocked] = useState(0);
  // false on both SSR and first client render so hydration matches; an effect
  // reads sessionStorage afterwards and may flip this for the short path.
  const [seen, setSeen] = useState(false);
  // resolved on the client (after mount) so we never touch window during render
  const [reduce, setReduce] = useState(false);
  const [faded, setFaded] = useState(false); // drives the short-path cross-fade
  const doneRef = useRef(false);
  // top, bottom, left, right — the order playIntroWindow() reads them in.
  const shutters = useRef<(HTMLDivElement | null)[]>([null, null, null, null]);

  const callDone = () => {
    if (!doneRef.current) {
      doneRef.current = true;
      // The hero OWNS the film's zoom wrapper; the loader only borrows it for
      // the reveal. Releasing here — rather than in the stage-1 effect — means
      // the SAFETY_CAP backstop and the short path get the same cleanup as the
      // normal exit, and the hero is never left carrying a forwards-filling
      // animation (and a promoted full-viewport layer) for the session.
      releaseIntroFilm();
      onDone();
    }
  };

  // Fail-safe: under no circumstances may the loader permanently block the page.
  // Independent of path, asset signals, or any per-stage effect, force the
  // hand-off at SAFETY_CAP. The doneRef guard above dedupes against the normal
  // exits, so this can only ever fire if something unforeseen stalled them.
  useEffect(() => {
    const safety = setTimeout(callDone, SAFETY_CAP);
    return () => clearTimeout(safety);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    setVp({ w: window.innerWidth, h: window.innerHeight });
    setReduce(window.matchMedia("(prefers-reduced-motion: reduce)").matches);
    // mark the intro as seen for next time; reading is wrapped for privacy mode
    try {
      if (sessionStorage.getItem(SEEN_KEY) === "1") setSeen(true);
      sessionStorage.setItem(SEEN_KEY, "1");
    } catch {
      /* sessionStorage unavailable (privacy mode / quota) — treat as first visit */
    }
  }, []);

  // reduced motion forces the short path regardless of session state
  const shortPath = reduce || seen;

  // Drive loading progress from real asset signals + a minimum display time.
  useEffect(() => {
    let cancelled = false;
    let assetsDone = false;
    let minDone = false;
    const finish = () => {
      if (assetsDone && minDone && !cancelled) {
        setProgress(100);
        setReady(true);
      }
    };

    // trickle up to ~90% so the bar always feels alive
    const trickle = setInterval(() => {
      setProgress((p) => (p < 90 ? Math.min(90, p + (p < 55 ? 3 : 1.4)) : p));
    }, 130);

    const minT = setTimeout(
      () => {
        minDone = true;
        finish();
      },
      shortPath ? MIN_TIME_REPEAT : MIN_TIME,
    );

    // wait on fonts + the hero video being playable
    let pending = 0;
    const done = () => {
      pending -= 1;
      if (pending <= 0) {
        assetsDone = true;
        finish();
      }
    };
    const cleanups: Array<() => void> = [];

    pending += 1;
    (document.fonts?.ready ?? Promise.resolve()).then(done);

    pending += 1;
    // the hero <video> may not have mounted yet when this effect runs —
    // poll a short window before concluding there is none
    const searchStart = performance.now();
    let raf = 0;
    const findVideo = () => {
      const v = document.querySelector("video");
      if (v) {
        if (v.readyState >= 3) done();
        else {
          const h = () => done();
          v.addEventListener("canplay", h, { once: true });
          cleanups.push(() => v.removeEventListener("canplay", h));
        }
        return;
      }
      if (performance.now() - searchStart < VIDEO_WAIT) {
        raf = requestAnimationFrame(findVideo);
      } else {
        done();
      }
    };
    raf = requestAnimationFrame(findVideo);
    cleanups.push(() => cancelAnimationFrame(raf));

    const cap = setTimeout(() => {
      assetsDone = true;
      minDone = true;
      finish();
    }, HARD_CAP);

    return () => {
      cancelled = true;
      clearInterval(trickle);
      clearTimeout(minT);
      clearTimeout(cap);
      cleanups.forEach((f) => f());
    };
  }, [shortPath]);

  // short path: once ready, cross-fade the cream overlay away then hand off
  useEffect(() => {
    if (!shortPath || !ready) return;
    setFaded(true);
    const t = setTimeout(callDone, FADE_MS);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [shortPath, ready]);

  // full path: start the split once every flap has locked in (or a cap elapses)
  useEffect(() => {
    if (shortPath || !ready) return;
    const allLocked = locked >= LETTERS.length;
    const t = setTimeout(() => {
      // Aim the hero film at the one shot that can carry the whole reveal —
      // see HERO_SEEK_S's note for the cut map and why neither 0 nor the
      // 6.00 keyframe will do. 5.84 is NOT a keyframe (nearest IDR 4.68):
      // the ~29 P-frame decode costs ~8ms, measured, and it happens here,
      // BEFORE stage 1's first animated frame, without dropping readyState.
      // Buffer-guarded so a cold cache degrades to the head of the clip —
      // yesterday's behaviour — rather than a blank window on unbuffered
      // film.
      const v = document.querySelector("video");
      if (v && v.readyState >= 2) {
        let buffered = false;
        for (let i = 0; i < v.buffered.length; i++)
          if (
            v.buffered.start(i) <= HERO_SEEK_S &&
            HERO_SEEK_S < v.buffered.end(i)
          )
            buffered = true;
        try {
          v.currentTime = buffered ? HERO_SEEK_S : 0;
        } catch {
          /* seek refused — the film simply keeps its current position */
        }
      }
      setStage(1);
    }, allLocked ? 380 : SETTLE_CAP);
    return () => clearTimeout(t);
  }, [shortPath, ready, locked]);

  // ── THE REVEAL ITSELF ──
  // Stage 1 hands the whole window to lib/introWindow.ts: four cream shutters
  // and the hero's film, all started from THIS ONE CALL with one explicit
  // `startTime`, all on `transform`, all on the compositor. No piece of the
  // geometry is computed twice — see that module for why `k` is the only
  // number here, and for the two mechanisms that were built, measured and
  // rejected before it.
  //
  // WHY AN EFFECT AND NOT A `motion` PROP. The film lives in <Hero>, this
  // component's SIBLING, so it can only be reached imperatively through the
  // registry — and the shutters have to share the film's clock exactly or a
  // seam of hero background opens along the aperture edge. One imperative call
  // site is the only way all five get the same start time.
  useEffect(() => {
    if (shortPath || stage !== 1 || !vp) return;
    // The point of light as a FRACTION of the viewport, so `k` can be driven
    // straight from it. SEED_PX_MIN is absolute on purpose — see its note.
    const kPoint = SEED_PX_MIN / vp.w;
    // The hold's size as a fraction, under the same clamp its px constants
    // describe, so `k` can be driven straight from it at any viewport.
    const kHold =
      Math.min(Math.max(HOLD_MIN_PX, vp.w * HOLD_VW), vp.w * HOLD_MAX_VW) /
      vp.w;
    const anim = playIntroWindow({
      // FIVE KEYFRAMES, THREE OF WHICH ARE STILL. The first pair holds the
      // point under the veil; the middle pair IS the hold, and because both
      // carry the identical value the interpolation between them is exactly
      // still — no sub-pixel drift is even representable. The head exists
      // because the reveal's clock has to be REVEAL_MS long: every probe in
      // scripts/ identifies this animation by its duration, and a `delay`
      // would have made the animation's own currentTime disagree with the
      // timeline everything else is graded on.
      k: [kPoint, kPoint, kHold, kHold, 1],
      times: [0, T_WIN_OPEN, T_HOLD_IN, T_HOLD_OUT, REVEAL_MS].map(
        (t) => t / REVEAL_MS,
      ),
      ease: [HOLD, EASE_SETTLE, HOLD, SPRING_OUT],
      duration: REVEAL_MS,
      shutters: shutters.current,
      endInset: {
        top: insets.top / vp.h,
        bottom: insets.bottom / vp.h,
        side: insets.side / vp.w,
      },
    });
    // No elements means no reveal, and a loader that never finishes is worse
    // than one that cuts: fall straight through to the hand-off.
    if (!anim) {
      setStage(2);
      return;
    }
    let live = true;
    anim.finished.then(() => live && setStage(2)).catch(() => {});
    // Deliberately NOT cancelled on cleanup: the shutters must hold their final
    // `scale(0)` (and the film its identity) until the overlay unmounts
    // HANDOFF_MS later. callDone() is what releases the film.
    return () => {
      live = false;
    };
  }, [shortPath, stage, vp, insets]);

  // Full path: after the window has grown, hand control back to the page. The
  // insets are all zero, so the window is already full-bleed when the reveal
  // completes — there is no residual cream to cross-fade, and the old 540ms
  // hold here was half a second of a finished, frozen frame. HANDOFF_MS is
  // only a paint buffer; callDone stays idempotent via doneRef, and the
  // SAFETY_CAP failsafe above is untouched.
  useEffect(() => {
    if (stage !== 2) return;
    const t = setTimeout(callDone, HANDOFF_MS);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stage]);

  if (!vp)
    return (
      <div
        className={styles.overlay}
        /* ⚠️ THE LOADER IS A CREAM SHEET AT z-index 100 COVERING THE WHOLE
             VIEWPORT, AND ONLY SCRIPT DISMISSES IT. With JavaScript off it
             stands for ever: measured, the home page was a blank cream
             screen with the entire site correctly laid out underneath it.
             The <noscript> block in app/layout.tsx removes it — an intro
             animation that cannot play should not be a lid. */
        data-nojs-hide=""
        style={{ background: "var(--cream)" }}
        aria-hidden
      />
    );

  // ---- short path: just a cream overlay that cross-fades out ----------------
  if (shortPath) {
    return (
      <div className={styles.overlay} aria-hidden data-nojs-hide="">
        <motion.div
          className={styles.sheet}
          initial={{ opacity: 1 }}
          animate={{ opacity: faded ? 0 : 1 }}
          transition={{ duration: FADE_MS / 1000, ease: SMOOTH }}
        />
        <motion.div
          className={styles.progress}
          animate={{ opacity: faded ? 0 : 1 }}
          transition={{ duration: 0.3 }}
        >
          <div
            className={styles.bar}
            style={{ transform: `scaleX(${progress / 100})` }}
          />
          <span className={styles.count}>
          {Math.min(100, Math.round(progress))}
        </span>
        </motion.div>
      </div>
    );
  }

  // ---- full path: split-flap board + the four-shutter window ----------------
  // NOTHING IS COMPUTED HERE ANY MORE. This block used to build five
  // `clip-path: path()` strings and their `times` and per-segment easing
  // arrays, on every render of every stage. The window is one scalar on one
  // spring now, and the only place that needs it is the effect above, so the
  // render path is just markup.


  const lockInc = () => setLocked((n) => n + 1);

  return (
    <div className={styles.overlay} aria-hidden data-nojs-hide="">
      {/* ═══ THE WINDOW: FOUR CREAM SHUTTERS ═══
          Each is a FULL-VIEWPORT cream sheet anchored to one edge by its
          transform-origin, and each scales by exactly the same value —
          (1 − k) / 2 — because the aperture is centred and uniform. Together
          they leave a k·vw × k·vh hole in the middle of the screen, and the
          hero's film scales by that same k to fill it. See lib/introWindow.ts.

          THEY REPLACE A SINGLE `clip-path: path()` SHEET, which was not
          compositor-accelerated: 7.4‥8.2ms of paint on EVERY displayed frame
          against full-viewport paint records, ~1261 RasterTasks over the
          grow-out, 8 of 97 frames compositor-animated — and the film frozen at
          natural size behind it the whole time, which is why the reveal
          uncovered a picture instead of zooming one. These four animate
          `transform` and nothing else.

          THE INLINE TRANSFORM IS NOT DECORATION AND IT IS NOT REDUNDANT WITH
          THE ANIMATION. `scaleY(0.5)` / `scaleX(0.5)` IS k = 0, the shut
          state, and carrying it (with `will-change: transform` from the
          stylesheet) on the FIRST render of stage 0 is what promotes these
          layers during the 2.6s of split-flap idle. Promoting them at
          animation start instead measured a 100‑137ms hitch on every run —
          five new full-viewport layers built inside one frame. Do not
          "simplify" this to a bare div plus an animation. */}
      {SHUTTERS.map(({ cls, axis }, i) => (
        <div
          key={cls}
          ref={(el) => {
            shutters.current[i] = el;
          }}
          className={`${styles.shutter} ${styles[cls]}`}
          style={{ transform: `${axis}(0.5)` }}
        />
      ))}

      {/* THE VEIL, AND IT IS WHY THE FILM DOES NOT APPEAR FROM NOTHING.
          An unclipped cream sheet over the whole viewport, so it is invisible
          against the cream overlay and only ever veils what shows THROUGH the
          window. It holds until 260ms — by which point the window is already
          a ~3px point — then fades over 120ms. EASE_OUT is near-expo, so
          although it nominally ends at 320ms it is under 5% opacity within
          ~50ms of starting. Its whole job is that a point of light should
          MATERIALISE rather than hard-pop; it deliberately does NOT last long
          enough to be a reveal of its own, because the reader should be
          watching the dot grow, not watching a cream sheet clear.
          It must sit ABOVE the shutters and BELOW .letters: veiling the board
          would hide the very letters that are fading out underneath it. */}
      <motion.div
        className={styles.veil}
        initial={{ opacity: 1 }}
        animate={{ opacity: stage >= 1 ? 0 : 1 }}
        transition={
          stage >= 1
            ? { duration: VEIL_FADE_S, delay: VEIL_DELAY_S, ease: EASE_OUT }
            : { duration: 0 }
        }
      />

      {/* The board leaves in place. It does not travel, so no frame can catch
          a legible letter on a screen edge; it recedes 4% so the exit reads as
          a departure rather than a bulb going out. */}
      <motion.div
        className={styles.letters}
        initial={{ opacity: 1, scale: 1 }}
        animate={
          stage === 0
            ? { opacity: 1, scale: 1 }
            : { opacity: 0, scale: BOARD_RECEDE }
        }
        transition={
          stage === 0
            ? { duration: 0.4, ease: SMOOTH }
            : { duration: BOARD_FADE_S, ease: EASE_OUT }
        }
      >
        <span className={styles.board}>
          {LETTERS.map((ch, i) => (
            <FlipLetter
              key={i}
              final={ch}
              settle={ready}
              startDelay={i * 55}
              reduce={false}
              onLock={lockInc}
            />
          ))}
        </span>
      </motion.div>

      <motion.div
        className={styles.progress}
        animate={{ opacity: stage >= 1 ? 0 : 1 }}
        transition={{ duration: 0.25, ease: EASE_OUT }}
      >
        <div
          className={styles.bar}
          style={{ transform: `scaleX(${progress / 100})` }}
        />
        <span className={styles.count}>
          {Math.min(100, Math.round(progress))}
        </span>
      </motion.div>
    </div>
  );
}
